#!/bin/bash
(ls -A1 --group-directories-first --sort=version; ls -d . ..) | awk '{ if (substr($0, length($0), 1) == "/") {printf $0 ","} else {printf $0 "/,"}}' | awk '{print substr($0, 1, length($0)-1)}'
